<?php

namespace Tests\Feature;

use App\Models\Bloc_cours;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class Bloc_coursTest extends TestCase
{
    use RefreshDatabase;
    private Bloc_cours $bloc_cours;
    /**
     * @author Philippe Bertrand
     *
     * A basic feature test example.
     */
    public function test_index(): void
    {
        //Vue show
        $response = $this->get('/bloc_cours');

        $response->assertStatus(200);

        $response->assertSee('Liste des blocs de cours actuels :');

        $response = $this->get('/bloc_cour');

        $response->assertStatus(404);

    }
    public function test_create_view(): void
    {
        //Vue de création
        $response = $this->get('/bloc_cours/nouveau');

        $response->assertStatus(200);

        $response->assertSee('Nouveau bloc de cours !');

        $response = $this->get('bloc_cours/nouvo');

        $response->assertStatus(500);
    }

    public function test_show(): void
    {
        $reponse = $this->get("/bloc_cours/{$this->bloc_cours->id}");
        $reponse->assertStatus(200);
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->bloc_cours = Bloc_cours::factory(1)->createOne([
            'jour'=> '4',
            'heures' => '00001111000011110000',
        ]);

        //Création d'un setup qui détecte une colonne inconnu
        /*
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->bloc_cours = Bloc_cours::factory(1)->createOne([
            'jour'=> '4',
            'heures' => '00001111000011110000',
            'champ_erreur' => -1
        ]); */
    }

    public function testDatabaseMissing()
    {
        $this->assertDatabaseMissing('bloc_cours',[
            'jour' => '1',
            'heures' => '11111111000000001111',
        ]);

        //Utiliser ce test avec un bloc de cours qui existe pour voir si le test échoue

        /* $this->assertDatabaseMissing('bloc_cours',[
             'jour' => '4',
             'heures' => '11111111000000001111',

         ]); */
    }

    public function testDatabaseHas()
    {
        $this->assertDatabaseHas('bloc_cours',[
            'jour' => '4',
            'heures' => '00001111000011110000',
        ]);

        // Création d'un bloc de cours qui n'existe pas pour détecter une erreur

         /*   $this->assertDatabaseHas('bloc_cours',[
            'jour' => '1',
            'heures' => '11111111000000001111',
        ]); */

    }

}

